apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: jobset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jobset
  name: jobset-prometheus-k8s
  namespace: openshift-jobset-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobset-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
